### ISSUE TITLE
Task 01 check_result runtime error

### ISSUE THREAD

**Issue by devopskupryk** [ViktorUJ/cks#135]
How to reproduce:
TASK=01 make run_cks_task
ssh ubuntu@ip_address
make steps from the [SOLUTION](https://github.com/ViktorUJ/cks/blob/master/docs/..%2Ftasks%2Fcks%2Flabs%2F01%2FSOLUTION.MD)
check_result

Result:
```
ubuntu@worker:~> check_result
 ✓ 0  Init  

1 test, 0 failures
Runtime error (func=(main), adr=9): Divide by zero
 result =  %   ok_points=0  all_points=0  
time_left=270 minutes
you  spend 29 minutes
```

**Comment by ViktorUJ** [comment]
it is ok . This lab don't have  auto test . Use SOLUTION file
