### ISSUE TITLE
Right way to disable state locking

### ISSUE THREAD

**Issue by devopskupryk** [ViktorUJ/cks#143]
Hi,

I'd got some network issue during "make run_cks_task".
I have locked state now and can't make neither  run_cks_task nor run_cks_task_clean nor delete_cks_task

What is right way to disable state locking?

**Comment by ViktorUJ** [comment]
Hi .
Login to aws console . 
go to dynamoDB (region get from terrafom/environments/terragrunt.hcl     default - **eu-north-1**)
find Table with locks 
delete item with  your env

**Comment by ViktorUJ** [comment]
@devopskupryk  , can I close  issue ?

**Comment by devopskupryk** [comment]
Thanks for your solution.
You can close this issue.
