### ISSUE TITLE
CKS TASK19. RUN groupadd myuser

### ISSUE THREAD

**Issue by devopskupryk** [ViktorUJ/cks#146]
Hi,

Why should I create myuser group explicitly?
Usedadd command creates default\primary group (with the same name) for creating user, doesn't it?

**Comment by ViktorUJ** [comment]
you can use any way

**Comment by ViktorUJ** [comment]
but check user and group

**Comment by devopskupryk** [comment]
```
podman logs cks-14
uid=1000(myuser) gid=1000(myuser) groups=1000(myuser)
```

This is right result, isn't it?
