### ISSUE TITLE
docs / Incorrect service name

### ISSUE THREAD

**Issue by sergiochoo** [ViktorUJ/cks#153]
Please fix a wrong service name in the doc: https://github.com/ViktorUJ/cks/blob/master/docs/..%2Ftasks%2Fcka%2Flabs%2F03%2FREADME.MD.

Should be like this:
service : name  meg-service2 -> deployment  meg-app2
ingress : name  meg-app2 -> service  meg-service2 , route to the same address  curl http://ckad.local:30102/app but with header X-Appversion=v2

Because the service in this lab is created with a name "meg-service", and not "meg-app".
***
Same for the 4th lab: https://github.com/ViktorUJ/cks/tree/master/tasks/cka/labs/04

**Comment by ViktorUJ** [comment]
I'll check it tomorrow
