### ISSUE TITLE
Typo in README.MD CKA 2 mock question 19

### ISSUE THREAD

**Issue by vodila-privet** [ViktorUJ/cks#160]
I found the typo in the pod's name in the 19th question.
 - Create static pod `stat-pod`
 - Acceptance criteria - Pod name: `stat-podv'

**Comment by ViktorUJ** [comment]
Hello,
Please create PR

**Comment by ViktorUJ** [comment]
https://github.com/ViktorUJ/cks/pull/161/files

**Comment by ViktorUJ** [comment]
done
