### ISSUE TITLE
Local Kubernetes Run

### ISSUE THREAD

**Issue by stevelaclasse** [ViktorUJ/cks#164]
Hi and Thanks you for this wonderful project.
I see that it is strictly combined with AWS.
I wanted to know with changes can i operate to run it on my local Kubernetes instance ?

Thanks

**Comment by ViktorUJ** [comment]
Hello. Yes , but node you need create manually.

**Comment by ViktorUJ** [comment]
you can find scripts https://github.com/ViktorUJ/cks/tree/master/terraform/modules/k8s_self_managment_v2/template

**Comment by stevelaclasse** [comment]
It will be very helpful, if we could have a little documentation on How to run a scenario on local Kubernetes cluster.

**Comment by ViktorUJ** [comment]
I'm sorry. I don't have any time to do it. You can use aws. The cost is very small.
